# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DE.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(576, 288)
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(8, 83, 255, 255), stop:0.334975 rgba(41, 95, 244, 255), stop:0.660099 rgba(37, 102, 244, 255), stop:1 rgba(6, 73, 233, 255))")
        self.p_2 = QtWidgets.QPushButton(Form, clicked= lambda: self.press("2"))
        self.p_2.setGeometry(QtCore.QRect(140, 110, 51, 71))
        self.p_2.setStyleSheet("font: 20pt \"Times\";")
        self.p_2.setObjectName("p_2")
        self.p_4 = QtWidgets.QPushButton(Form, clicked= lambda: self.press("4"))
        self.p_4.setGeometry(QtCore.QRect(240, 110, 51, 71))
        self.p_4.setStyleSheet("font: 20pt \"Times\";")
        self.p_4.setObjectName("p_4")
        self.p_3 = QtWidgets.QPushButton(Form, clicked= lambda: self.press("3"))
        self.p_3.setGeometry(QtCore.QRect(190, 110, 51, 71))
        self.p_3.setStyleSheet("font: 20pt \"Times\";")
        self.p_3.setObjectName("p_3")
        self.p_1 = QtWidgets.QPushButton(Form, clicked= lambda: self.press("1"))
        self.p_1.setGeometry(QtCore.QRect(90, 110, 51, 71))
        self.p_1.setStyleSheet("font: 20pt \"Times\";")
        self.p_1.setObjectName("p_1")
        self.p_0 = QtWidgets.QPushButton(Form, clicked= lambda: self.press("0"))
        self.p_0.setGeometry(QtCore.QRect(40, 110, 51, 71))
        self.p_0.setStyleSheet("font: 20pt \"Times\";")
        self.p_0.setObjectName("p_0")
        self.p_7 = QtWidgets.QPushButton(Form, clicked= lambda: self.press("7"))
        self.p_7.setGeometry(QtCore.QRect(390, 110, 51, 71))
        self.p_7.setStyleSheet("font: 20pt \"Times\";")
        self.p_7.setObjectName("p_7")
        self.p_9 = QtWidgets.QPushButton(Form, clicked= lambda: self.press("9"))
        self.p_9.setGeometry(QtCore.QRect(490, 110, 51, 71))
        self.p_9.setStyleSheet("font: 20pt \"Times\";")
        self.p_9.setObjectName("p_9")
        self.p_8 = QtWidgets.QPushButton(Form, clicked= lambda: self.press("8"))
        self.p_8.setGeometry(QtCore.QRect(440, 110, 51, 71))
        self.p_8.setStyleSheet("font: 20pt \"Times\";")
        self.p_8.setObjectName("p_8")
        self.p_6 = QtWidgets.QPushButton(Form, clicked= lambda: self.press("6"))
        self.p_6.setGeometry(QtCore.QRect(340, 110, 51, 71))
        self.p_6.setStyleSheet("font: 20pt \"Times\";")
        self.p_6.setObjectName("p_6")
        self.p_5 = QtWidgets.QPushButton(Form, clicked= lambda: self.press("5"))
        self.p_5.setGeometry(QtCore.QRect(290, 110, 51, 71))
        self.p_5.setStyleSheet("font: 20pt \"Times\";")
        self.p_5.setObjectName("p_5")
        self.p_p = QtWidgets.QPushButton(Form, clicked= lambda: self.press("+"))
        self.p_p.setGeometry(QtCore.QRect(40, 190, 71, 41))
        self.p_p.setStyleSheet("font: 20pt \"Times\";")
        self.p_p.setObjectName("p_p")
        self.p_n = QtWidgets.QPushButton(Form, clicked= lambda: self.press("-"))
        self.p_n.setGeometry(QtCore.QRect(120, 190, 71, 41))
        self.p_n.setStyleSheet("font: 20pt \"Times\";")
        self.p_n.setObjectName("p_n")
        self.p_t = QtWidgets.QPushButton(Form, clicked= lambda: self.press("*"))
        self.p_t.setGeometry(QtCore.QRect(200, 190, 71, 41))
        self.p_t.setStyleSheet("font: 20pt \"Times\";")
        self.p_t.setObjectName("p_t")
        self.p_m = QtWidgets.QPushButton(Form, clicked= lambda: self.press("/"))
        self.p_m.setGeometry(QtCore.QRect(280, 190, 71, 41))
        self.p_m.setStyleSheet("font: 20pt \"Times\";")
        self.p_m.setObjectName("p_m")
        self.p_e = QtWidgets.QPushButton(Form, clicked= lambda: self.answerrrr())
        self.p_e.setGeometry(QtCore.QRect(440, 190, 101, 91))
        self.p_e.setStyleSheet("font: 20pt \"Times\";")
        self.p_e.setObjectName("p_e")
        self.p_point = QtWidgets.QPushButton(Form, clicked= lambda: self.something("."))
        self.p_point.setGeometry(QtCore.QRect(360, 190, 71, 41))
        self.p_point.setStyleSheet("font: 20pt \"Times\";")
        self.p_point.setObjectName("p_point")
        self.l_l = QtWidgets.QLabel(Form)
        self.l_l.setGeometry(QtCore.QRect(50, 30, 491, 51))
        self.l_l.setStyleSheet("font: 75 24pt \"Times\";")
        self.l_l.setObjectName("l_l")
        self.p_c = QtWidgets.QPushButton(Form, clicked= lambda: self.something("C"))
        self.p_c.setGeometry(QtCore.QRect(40, 240, 191, 41))
        self.p_c.setStyleSheet("font: 20pt \"Times\";")
        self.p_c.setObjectName("p_c")
        self.p_ce = QtWidgets.QPushButton(Form, clicked= lambda: self.something("CE"))
        self.p_ce.setGeometry(QtCore.QRect(240, 240, 191, 41))
        self.p_ce.setStyleSheet("font: 20pt \"Times\";")
        self.p_ce.setObjectName("p_ce")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.p_2.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.p_2.setText(_translate("Form", "2"))
        self.p_4.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.p_4.setText(_translate("Form", "4"))
        self.p_3.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.p_3.setText(_translate("Form", "3"))
        self.p_1.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.p_1.setText(_translate("Form", "1"))
        self.p_0.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.p_0.setText(_translate("Form", "0"))
        self.p_7.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.p_7.setText(_translate("Form", "7"))
        self.p_9.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.p_9.setText(_translate("Form", "9"))
        self.p_8.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.p_8.setText(_translate("Form", "8"))
        self.p_6.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.p_6.setText(_translate("Form", "6"))
        self.p_5.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.p_5.setText(_translate("Form", "5"))
        self.p_p.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.p_p.setText(_translate("Form", "+"))
        self.p_n.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.p_n.setText(_translate("Form", "-"))
        self.p_t.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.p_t.setText(_translate("Form", "*"))
        self.p_m.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.p_m.setText(_translate("Form", "/"))
        self.p_e.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.p_e.setText(_translate("Form", "="))
        self.p_point.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.p_point.setText(_translate("Form", "."))
        self.l_l.setText(_translate("Form", "<html><head/><body><p></p></body></html>"))
        self.l_l.setText('0')
        self.p_c.setText(_translate("Form", "C"))
        self.p_ce.setText(_translate("Form", "CE"))

    def press(self, pressed):
        if self.l_l.text() == '' or self.l_l.text() == '0':
            self.l_l.setText(pressed)
        else:
            self.l_l.setText(f'{self.l_l.text()}{pressed}')

    def something(self, pressed):
        screen = self.l_l.text()
        if pressed == "CE":
            AAA = self.l_l.text()
            if len(screen) > 1:
                self.l_l.setText(AAA[:-1])
            else:
                self.l_l.setText('0')
        elif pressed == "C":
            self.l_l.setText("0")
        elif pressed == ".":
            if screen[len(screen)-1] == '.':
                pass
            else:
                self.l_l.setText(f'{screen}.')

    def pntm(self,pressed):
        if self.l_l.text() == '0':
            pass
        else:
            self.l_l.setText(f'{self.l_l.text()}{pressed}')

    def answerrrr(self):
        screen = self.l_l.text()
        ans = eval(screen)
        try:
            self.l_l.setText(str(ans))
        except:
            self.l_l.setText('Error')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
